# Generated by Django 4.1.1 on 2022-12-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("industry", models.CharField(max_length=128)),
                ("place", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("real_name", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=128)),
                ("password", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=10,
                    ),
                ),
            ],
            options={"ordering": ["id"],},
        ),
        migrations.CreateModel(
            name="Adminer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="login.user",
                    ),
                ),
            ],
            bases=("login.user",),
        ),
        migrations.CreateModel(
            name="PosPublisher",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="login.user",
                    ),
                ),
            ],
            bases=("login.user",),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="login.user",
                    ),
                ),
                ("school_name", models.CharField(max_length=128)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("大一", "大一"),
                            ("大二", "大二"),
                            ("大三", "大三"),
                            ("大四", "大四"),
                            ("研一", "研一"),
                            ("研二", "研二"),
                            ("研三", "研三"),
                            ("博一", "博一"),
                            ("博二", "博二"),
                        ],
                        default="大四",
                        max_length=10,
                    ),
                ),
                ("major", models.CharField(max_length=128)),
            ],
            bases=("login.user",),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1024)),
                ("last_update_time", models.DateTimeField()),
                (
                    "last_update_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=256)),
                ("demanding", models.CharField(max_length=256)),
                ("salary", models.IntegerField()),
                (
                    "enterprise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.enterprise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=256)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_receiver",
                        to="login.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sender",
                        to="login.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1024)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.pospublisher",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "pospublisher_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="login.pospublisher",
                    ),
                ),
                ("profession_title", models.CharField(max_length=128)),
                ("research_direction", models.CharField(max_length=128)),
                (
                    "lab_belonging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.lab",
                    ),
                ),
            ],
            bases=("login.pospublisher",),
        ),
        migrations.CreateModel(
            name="SchoolMate",
            fields=[
                (
                    "pospublisher_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="login.pospublisher",
                    ),
                ),
                ("school_name", models.CharField(max_length=128)),
                ("work_field", models.CharField(max_length=128)),
                (
                    "enterprise_belonging",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.enterprise",
                    ),
                ),
            ],
            bases=("login.pospublisher",),
        ),
    ]
