# Generated by Django 4.1.1 on 2022-12-02 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="enterprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.pospublisher",
            ),
        ),
    ]
