# Generated by Django 4.1.1 on 2022-12-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_alter_position_enterprise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="position", old_name="enterprise", new_name="posPublisher",
        ),
    ]
